services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
    networks:
      - zava-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=container
      - postgres_host=db
      - postgres_port=5432
      - postgres_user=postgres
      - postgres_password=P@ssw0rd!
      - postgres_db=zava
